name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *" # Har 12 soatda ishga tushadi

  workflow_dispatch: # Qo'lda ishga tushirish imkoniyati

  push:
    branches:
      - master # Master branchga push qilinganda ishga tushadi

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: BexruzBerdimurodov # Bu yerda foydalanuvchi nomingiz
          outputs: dist/snake.svg
          palette: github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # Tokenni to‘g‘ri qo‘llash
