name: Generate snake animation

on:
  workflow_dispatch
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.BexruzBerdimurodov }}
          github_token: ${{ secrets.GH_PAT }}
          outputs: dist/snake.svg

      - name: Commit and push changes
        run: |
          git config --global user.email "umidjonovichuz@gmail.com"
          git config --global user.name "BexruzBerdimurodov"
          git add dist/snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
